-- update CAMPAIGNPROJECT_CAMPAIGN_BANNER_POSITION set BANNER_POSITION_ID = <default_value> where BANNER_POSITION_ID is null ;
alter table CAMPAIGNPROJECT_CAMPAIGN_BANNER_POSITION alter column BANNER_POSITION_ID set not null ;
